### ISSUE TITLE
Access on the PRs

### ISSUE THREAD

**Issue by StevenPuttemans** [StevenPuttemans/opencv#4]
@alalek, I would like to ask you how it is possible that all of a sudden I have obtained the rights to accept PR's into the official OpenCV repo. I have opened it here to keep it out of the attention of others until my role is clear.

![screenshot from 2016-03-08 15 21 20](https://cloud.githubusercontent.com/assets/4621239/13604099/7717e10e-e541-11e5-9f3e-209d96e5b19b.png)

As you can see I am able to press the merge PR button, which I did not before. Is this intended? If so I thank the team for the trust, if not, we might want to solve this?

**Comment by StevenPuttemans** [comment]
I also noticed I can now close down issues on github on OpenCV which I could not do before!

**Comment by alalek** [comment]
I believe it is during of providing write access for you to OpenCV Wiki. Unfortunately we did't found another way to do this, so we allow full write access to OpenCV repository (so it is not only access to this button, actually).
But please don't use this button, results may be overwritten later by our merging bot (also we use different merge commit message than GitHub default).

We want to disable this button completely, but it is not supported by GitHub yet (To eliminate accidental clicks I use adblock-like plugin and hide button)

@mshabunin and @vpisarev can add something about this.

**Comment by StevenPuttemans** [comment]
@alalek thank you for the update :) I will keep it clean and try to avoid hitting the merge button. Does this mean that I can lure the buildbot using the :+1: statement on a PR?

**Comment by alalek** [comment]
Buildbot checks :+1: or :shipit: from assignee person only, but it doesn't merge anything automatically only by separate request.

**Comment by StevenPuttemans** [comment]
Aha! Good to know. Well as said, I will then keep my hand of the merge button, but I will use my privileges on the wiki and the issues tab to help people further! Thanks again!
