### ISSUE TITLE
Issue with VideoCapture and cvtColor

### ISSUE THREAD

**Issue by StevenPuttemans** [StevenPuttemans/opencv#5]
@alalek I am calling you here to ask for your opinion on an OpenCV matter.

I am working with a student on optimizing/speeding up the cascade classifier process. Now for that, he is grabbing negatives from provided video files and putting them into a vector (for now, lets assume this works). What he does is the following:

```
vector<Mat> populate(string videoFileName)
{
    VideoCapture videoFileToBeProcessedSub(videoFileName);
    vector<Mat> videoSub;
    Mat videoFrameSub;

    cout << "Populating vector..." << endl;
    while (videoFileToBeProcessedSub.read(videoFrameSub))
    {
        cvtColor(videoFrameSub, videoFrameSub, CV_BGR2GRAY);
        videoSub.push_back(videoFrameSub);
    }
    cout << "Vector populated" << endl;

    return videoSub;
}
```

Now the problem is that when running this code, the VideoCapture and cvtColor generate threads (performance speedup in OpenCV) to process data faster, but when leaving the function, the garbage collector is only removing threads used by VideoCapture. The cvtColor threads keep lurking around.

You got any idea why this is happening?

@canergun can provide more info on this matter if you need it!

**Comment by alalek** [comment]
I believe these cvtColor threads are created by `parallel_for_()` construction. They are thread pool threads, this count should not grow a lot. You may take a look on `cv::setNumThreads()` call (especially with "1" argument: `setNumThreads(1)` - this should disable parallel processing)

**Comment by StevenPuttemans** [comment]
thanks, we will look into it!

**Comment by canergun** [comment]
Thanks!

**Comment by canergun** [comment]
after i called setNumThreads(1) the VideoCapture initialization and cvtColor processing still used multiple threads but they cleaned them afterwards when they went out of scope

**Comment by PkLab** [comment]
I was landed here running around OpenCV github relocation.... Sorry to jump in this discussion but I would to underline that `videoSub.push_back(videoFrameSub);` does't create a copy onto videoSub but just a ref. It works only because sequence `read color ->cvtColor->read color` creates a new Mat each time. Maybe this is your intent maybe is the root of the issue

For example this small variation won't work as expected... all frames in the vector will be same as last one.

```cpp
    while (videoFileToBeProcessedSub.read(videoFrameSub))
    {
        cvtColor(videoFrameSub, grayFrame, CV_BGR2GRAY);
        videoSub.push_back(grayFrame);
```
I would suggest to check if this version works better

```cpp
	cvtColor(videoFrameSub, grayFrame, CV_BGR2GRAY);
	videoSub.push(Mat(grayFrame.size(), grayFrame.type()));
	grayFrame.copyTo(videoSub.back());
```

**Comment by StevenPuttemans** [comment]
Thanks!
